name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean test

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        generate-branch-badge: true
        branch-name: main

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: target/site/jacoco/jacoco.xml
